### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by AyudantesTecnicas** [PabloFederico/template-tp-grupal#1]
Tienen que definir cual va a ser su workflow en Git. Pueden dejarlo especificado en una página de la Wiki.

https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by BatagliaMatias** [comment]
El workflow que vamos a utilizar es Feature Branch Workflow

[https://github.com/PabloFederico/template-tp-grupal/wiki/Git-Workflow](url)
