### ISSUE TITLE
Temple Quest - Explicar impacto o como se encara incorporar este nuevo juego

### ISSUE THREAD

**Issue by AyudantesTecnicas** [PabloFederico/template-tp-grupal#3]
Subir el link a una wiki page: /template-tp-grupal/wiki/Analisis-del-Temple-Quest, donde expliquen brevemente, que es necesario hacer usando la implementación actual del motor de juegos de aventura gráfica para soportar este nuevo juego, por ejemplo, crear una clase para modelar el Juego que extienda a la clase Game, crear tal otras clases extendiendo del modelo tal, configurar tales cosas, etc, etc segun sea necesario para que alguien usando su motor pueda crear o configurar este nuevo juego.
Si hay algo que el diseño actual no lo permite y es necesario hacer algún cambio o agregar algo nuevo al modelo indíquenlo también. 
Esta actividad era la que se debía hacer en clase y enviar a su ayudante, por favor subanla a la wiki indicada y cierren el ticket cuanto antes. Gracias

**Comment by mafvidal** [comment]
Cierro el issue, la explicación a la actividad se encuentra en https://github.com/PabloFederico/template-tp-grupal/wiki/Actividad-1er-Entrega
