### ISSUE TITLE
Vi que hay un enum con las actions, eso impide que se agreguen nuevas actions facilmente, se les ocurre alguna alternativa?

### ISSUE THREAD

**Issue by carloscurotto** [PabloFederico/template-tp-grupal#5]

**Comment by carloscurotto** [comment]
Lo mismo que GameEnum

**Comment by BatagliaMatias** [comment]
quizas se podría utilizar un map cargado dinamicamente con la clave valor <String,Factory> para GameEnum

**Comment by PabloFederico** [comment]
quizás cambiar lo que es la estructura de un enum y pensarlo mas como una interfaz con actions que la implementen

**Comment by jorlando** [comment]
se borro el gameEnum, ahora recibe el jar por parametro
