### ISSUE TITLE
Agreguen tests unitarios, hay algunos tests pero no son tan unitarios, sino mas bien de caja negra, testean cada juego completo

### ISSUE THREAD

**Issue by carloscurotto** [PabloFederico/template-tp-grupal#7]

**Comment by jorlando** [comment]
Coverage Actual: 55%
La idea es mejorarlo.
![coverage](https://cloud.githubusercontent.com/assets/1566144/15269493/97fb43ce-19d6-11e6-9b2d-6e218008fdc8.png)
